### ISSUE TITLE
galaxyxml seemingly missing in the Galaxy ToolFactory Appliance

### ISSUE THREAD

**Issue by fabrice-ducos** [fubar2/toolfactory#4]
Hello,

I have been investigating the ToolFactory for Galaxy.

I follow the [Hello World! with the ToolFactory Appliance](https://training.galaxyproject.org/training-material/topics/dev/tutorials/tool-generators/tutorial.html) Tutorial.

I carefully follow the steps in the tutorial (installing the Galaxy ToolFactory Appliance with docker-compose). However, when executing the "Hello" tool, it fails with the following error.

```
Traceback (most recent call last):
  File "/galaxy-central/database/shed_tools/toolshed.g2.bx.psu.edu/repos/fubar_too/toolfactory/f9fb7c57cccb/toolfactory/toolfactory/toolfactory.py", line 33, in <module>
    import galaxyxml.tool as gxt
ModuleNotFoundError: No module named 'galaxyxml'
```

It looks like that [galaxyxml](https://github.com/fubar2/galaxyxml)  is missing in the Galaxy ToolFactory Docker container, at least in the version available at the time of writing.

**Comment by fubar2** [comment]
Sorry about that - it's been unloved for some time - let me take a look - it sounds like the toolfactory failed to install properly. I may point you toward a simpler way of getting it going but I better test that first :)

**Comment by fabrice-ducos** [comment]
Dear Ross, thank you so much for your quick reply!

Have a nice day :)

**Comment by fubar2** [comment]
@fabrice-ducos - The most recent revision seems to be working - see https://github.com/fubar2/galaxy_tf_overlay#readme , but not in docker yet, sorry.

There is a PR under construction to update the GTN tutorial, running as a preview here: https://training.galaxy.lazarus.name/training-material/topics/dev/tutorials/tool-generators/tutorial.html

Thanks for reminding me that the current GTN one is broken. Been working on it for a while but got distracted. 
If you have time to try the updated tutorial material out and let me know what would make it better, that would help me a lot before I merge the updates! 

A docker version is coming but it will not be persistent between docker image restarts.
The user will need to explicitly export, save and restore histories from the running docker image, to persist any important work - but it will be ideal for testing it out. 

For real work a local desktop install https://github.com/fubar2/galaxy_tf_overlay is probably more useful but building the client during installation takes 20+ minutes - but it is a proper persistent development galaxy instance in a single directory, easily destroyed when no longer needed. 

Docker should be done soon and I'll update the draft and submit a pull requiest to update the GTN material.

**Comment by fubar2** [comment]
Update: docker image is available to test,
```
docker pull quay.io/fubar2/galaxy_toolfactory:latest
docker run -d -p 8080:8080 quay.io/fubar2/galaxy_toolfactory:latest
```
Watch the docker log until the web server is ready, then http://localhost:8080 
Login is required - account details in the preview.

**Comment by fubar2** [comment]
@fabrice-ducos: Good news - the PR is merged so the GTN version is now up to date.
Feedback is welcomed if you have time to take another look - please close this issue if it is resolved for you?

The docker image is a relatively quick way to get started and seems stable to my limited testing.

**Comment by fabrice-ducos** [comment]
Dear @fubar2 

those are great news!

I may not have much time to check again before the end of next week but I will definitely try and keep you informed.

Thank you so much and best wishes!

**Comment by fabrice-ducos** [comment]
Dear @fubar2 

I have tested the new docker image. The GalaxyToolFactory now works perfectly for me now :)

A great tool, well documented, with a nice tutorial and video demonstration. A highly configurable, much better option than producing tools manually, in my opinion. And you have been so helpful and quick to answer!

I close this issue.

Thank you!

**Comment by fubar2** [comment]
Glad to hear it worked for you and thanks for the kind words, @fabrice-ducos - please spread the word :)
